### ISSUE TITLE
学长你好，可以分享下你这个文件夹的百度云链接码？马上要考单片机了有点急

### ISSUE THREAD

**Issue by Yin-Chen-0** [25thengineer/DSX_KCXG#1]

**Comment by 25thengineer** [comment]
没有百度云链接啊 ，兄嘚

**Comment by Yin-Chen-0** [comment]
Utah Xef
        您好！我已收到您的邮件。
        
        你这里不是写了嘛//
        可不可以加个好友发一下啊，灰常感谢。我也是工大的，我qq 1658720020
        🙏
       有什么问题随时与我联系和沟通，祝好！


2021-1-8
| |
陈银
|
|
17338404490
chenyin1050@163.com
|
签名由网易邮箱大师定制
在2021年1月8日 19:40，Utah Xef<notifications@github.com> 写道：

没有百度云链接啊 ，兄嘚
