### ISSUE TITLE
学长请问有操作系统A的实验报告的存档吗？

### ISSUE THREAD

**Issue by lythings** [25thengineer/DSX_KCXG#2]
最近考试比较多，自己实验完成的不是很好，如果学长方便的话，能把OS课的实验报告给我参考一下吗 QWQ
Email-Address: luyi404@qq.com

**Comment by 25thengineer** [comment]
我们上《操作系统A》时正值疫情严重，无法返校，上课都是线上，实验没有做。
田卫东老师本来说回学校要补实验的，后面也是不了了之。
